### ISSUE TITLE
Prisma

### ISSUE THREAD

**Issue by wsael** [appujet/WaveMusic#62]
[16.12.2023] [20:15:14] [interactionCreate.js] [Wavemusic] » ✖  error     PrismaClientKnownRequestError:  
Invalid `this.client.prisma.guild.findUnique()` invocation in
C:\Users\thews\Downloads\WaveMusic-main\src\commands\info\Help.js:39:54

  36 }
  37 async run(client, ctx, args) {
  38     const embed = this.client.embed();
→ 39     let prefix = (await this.client.prisma.guild.findUnique(
Raw query failed. Code: `unknown`. Message: `Kind: Command failed: Error code 8000 (AtlasError): empty database name not allowed
        at 0bde02f4548c36d068f33f3218b82677/atlasproxy/session_proxy.go:696
        at 0bde02f4548c36d068f33f3218b82677/atlasproxy/session_proxy.go:1594
        at 0bde02f4548c36d068f33f3218b82677/atlasproxy/session_proxy.go:1175
        at 10gen/mongonet@v0.0.0-20231003200030-cd8e79f175ea/proxy_session.go:364
        at 10gen/mongonet@v0.0.0-20231003200030-cd8e79f175ea/proxy_session.go:117
        at 10gen/mongonet@v0.0.0-20231003200030-cd8e79f175ea/session.go:217
        at 10gen/mongonet@v0.0.0-20231003200030-cd8e79f175ea/server.go:401
        at src/runtime/asm_arm64.s:1172, labels: {}`
    at Ig.handleRequestError (C:\Users\thews\Downloads\WaveMusic-main\node_modules\@prisma\client\runtime\binary.js:182:6819)
    at Ig.handleAndLogRequestError (C:\Users\thews\Downloads\WaveMusic-main\node_modules\@prisma\client\runtime\binary.js:182:6207)
    at Ig.request (C:\Users\thews\Downloads\WaveMusic-main\node_modules\@prisma\client\runtime\binary.js:182:5927)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async a (C:\Users\thews\Downloads\WaveMusic-main\node_modules\@prisma\client\runtime\binary.js:187:9983)
    at async Help.run (C:\Users\thews\Downloads\WaveMusic-main\src\commands\info\Help.js:39:23)
    at async InteractionCreate.run (C:\Users\thews\Downloads\WaveMusic-main\src\events\Client\interactionCreate.js:156:17)

**Comment by aryanjsingh** [comment]
Fix this error to add database name in end of the `DATABASE_URL` like this in .env file `mongodb+srv://xxyydd:ejejeje@cluster0.f93tcdq.mongodb.net/Bot`

**Comment by CanArslanDev** [comment]
I was having the same problem,
After mongodb.net/ I just typed the database name and it worked!

`mongodb+srv://glitch:12345@cluster0.f9zx9lw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0`
to
`mongodb+srv://glitch:12345@cluster0.f9zx9lw.mongodb.net/Cluster0`
