### ISSUE TITLE
Play issus

### ISSUE THREAD

**Issue by paracelp** [appujet/WaveMusic#66]
Error: The voice connection is not established in 15 seconds
    at Connection.connect (/home/container/node_modules/shoukaku/dist/index.js:369:15)
    at async Node.joinChannel (/home/container/node_modules/shoukaku/dist/index.js:1093:7)
Error: The voice connection is not established in 15 seconds
    at Connection.connect (/home/container/node_modules/shoukaku/dist/index.js:369:15)
    at async Node.joinChannel (/home/container/node_modules/shoukaku/dist/index.js:1093:7)
Error: The voice connection is not established in 15 seconds
    at Connection.connect (/home/container/node_modules/shoukaku/dist/index.js:369:15)
    at async Node.joinChannel (/home/container/node_modules/shoukaku/dist/index.js:1093:7)

**Comment by LucasB25** [comment]
Lavalink issues
